import AboutSection from "@/components/AboutSection";
import Problems from "@/components/Problems";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import TeamSection from "@/components/TeamSection";
import Head from "next/head";
import EcosystemSection from "@/components/EcosystemSection";
import EcosystemSectionTwo from "@/components/EcosystemSectionTwo";
import Roadmap from "@/components/Roadmap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header /> 
        <HeroSection />
        <AboutSection/>
        <Problems/>
        <EcosystemSection/>
        <EcosystemSectionTwo/>
      
        <Roadmap/>
        <TeamSection />
        <Footer />
    </>
  );
}
